apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

containerRuntimeEndpoint: unix:///var/run/cri-dockerd.sock
failSwapOn: false
cgroupsPerQOS: false
enforceNodeAllocatable: []

# Authentication & Authorization (permissive for standalone mode)
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow

staticPodPath: /etc/kubernetes/manifests
